server:
  port: 8081

spring:
  application:
    name: dairy-farm-management

  datasource:
    url: jdbc:mysql://localhost:3306/dairy_farm_management
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true